### ISSUE TITLE
Bug at purestorage.flasharray.purefa_volume (move volume)

### ISSUE THREAD

**Issue by SchmidtJonathan1** [Pure-Storage-Ansible/FlashArray-Collection#144]
**Describe the bug**
If you use "ansible-galaxy collection install purestorage.flasharray (v. 1.5.1)" there is a problem with "purestorage.flasharray.purefa_volume (move volume)" it returns a
error message: "InsecureRequestWarning: Unverified HTTPS request is being made"

At version 1.5.0 the error not exist.

**To Reproduce**
1. Run playbook
2. - name: Move volume
      purestorage.flasharray.purefa_volume:
          name: "{{ vol_name }}"
          move: "{{ vol_to_pod }}"
          fa_url: "{{ fa_url }}"
          api_token: "{{ fa_token }}"

4. Returns error message:
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n

**Comment by sdodsley** [comment]
This is not an issue or bug. 
If you want to add SSL certificates you can do that using other modules.
If you are using the verbose logging you will see this message for all modules

**Comment by SchmidtJonathan1** [comment]
Hello Simon,
Thanks for the answer. 
Is it normal that the playbook stop running? You say i can ignore the message, right?

**Comment by sdodsley** [comment]
Correct. This message is not fatal and will not cause the task to fail. 
Can you provide the full output from the playbook with the `-vvvv` switch?
I suspect you have provided incorrect information to the task.

**Comment by SchmidtJonathan1** [comment]
TASK [purity_active_cluster_setup : Move volume] ****************************************************************************************
task path: /home/****/Downloads/storage-pure/roles/purity_active_cluster_setup/tasks/main.yml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ****
<127.0.0.1> EXEC /bin/sh -c 'echo ~**** && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/****/.ansible/tmp `"&& mkdir "` echo /home/****/.ansible/tmp/ansible-tmp-1612290615.4699194-4495-190472444991409 `" && echo ansible-tmp-1612290615.4699194-4495-190472444991409="` echo /home/****/.ansible/tmp/ansible-tmp-1612290615.4699194-4495-190472444991409 `" ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume.py
<127.0.0.1> PUT /home/****/.ansible/tmp/ansible-local-4416ua3rocno/tmp5gscs599 TO /home/****/.ansible/tmp/ansible-tmp-1612290615.4699194-4495-190472444991409/AnsiballZ_purefa_volume.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/****/.ansible/tmp/ansible-tmp-1612290615.4699194-4495-190472444991409/ /home/****/.ansible/tmp/ansible-tmp-1612290615.4699194-4495-190472444991409/AnsiballZ_purefa_volume.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/****/.ansible/tmp/ansible-tmp-1612290615.4699194-4495-190472444991409/AnsiballZ_purefa_volume.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/****/.ansible/tmp/ansible-tmp-1612290615.4699194-4495-190472444991409/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => changed=false 
  module_stderr: |-
    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '***.***.***.***'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '***.***.***.***'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '***.***.***.***'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '***.***.***.***'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '***.***.***.***'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '***.***.***.***'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '***.***.***.***'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '***.***.***.***'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '***.***.***.***'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    /usr/lib/python3/dist-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host '***.***.***.***'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
      warnings.warn(
    Traceback (most recent call last):
      File "/home/****/.ansible/tmp/ansible-tmp-1612290615.4699194-4495-190472444991409/AnsiballZ_purefa_volume.py", line 102, in <module>
        _ansiballz_main()
      File "/home/****/.ansible/tmp/ansible-tmp-1612290615.4699194-4495-190472444991409/AnsiballZ_purefa_volume.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/***/.ansible/tmp/ansible-tmp-1612290615.4699194-4495-190472444991409/AnsiballZ_purefa_volume.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_volume', init_globals=None, run_name='__main__', alter_sys=True)
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_purestorage.flasharray.purefa_volume_payload_7s5i625c/ansible_purestorage.flasharray.purefa_volume_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume.py", line 886, in <module>
      File "/tmp/ansible_purestorage.flasharray.purefa_volume_payload_7s5i625c/ansible_purestorage.flasharray.purefa_volume_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume.py", line 861, in main
      File "/tmp/ansible_purestorage.flasharray.purefa_volume_payload_7s5i625c/ansible_purestorage.flasharray.purefa_volume_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume.py", line 726, in move_volume
    UnboundLocalError: local variable 'target_exists' referenced before assignment
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

**Comment by sdodsley** [comment]
@SchmidtJonathan1 - so you have actually found a bug.
We will raise a fix and get it into the next release of the Collections. I expect that release to be available by the end of the week.

**Comment by sdodsley** [comment]
Closed by #145
