### ISSUE TITLE
Bug creating volume using Purestorage-flasharray 1.6.2 or higher

### ISSUE THREAD

**Issue by RomainDusi** [Pure-Storage-Ansible/FlashArray-Collection#176]
**Describe the bug**
When trying to create a new volume on a pod, there is an error proventing the creation when using Purestorage-flasharray 1.6.2 or higher.

**To Reproduce**
Purestorage 1.19.0
Py-Pure-Client 1.8.0
Netaddr 0.8.0
Requests 2.25.1
Purestorage.flasharray 1.6.2 (ansible collection)

The bay is using Purity/FA 5.3.15
Also using self-signed certificate

Ansible Playbook :
---
  - name: Purestorage volume create or extend
    purefa_volume:
      name: pod-test::volume-test
      size: 2T
      fa_url: "{{hostname}}"
      api_token: "{{Api_Token}}"
      state: present
      
When lauching this playbook with Purestorage_flasharray 1.6.1, everything works fine and the volume is created on the bay, but when using Purestorage_flasharray 1.6.2 or higher there is an error (see attached).

[Error log.txt](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/6285874/Error.log.txt)

Note : If you try to create the same volume after upgrading from version 1.6.1 to version 1.6.2, no error is displayed as there is no change.

**Expected behavior**
The volume should be created on the bay without the error.

**Comment by sdodsley** [comment]
Thank you for reporting this issue.

A fix has been created and will be in the next release of the FlashArray
Collections.

In the interim, you can pull the fix from
https://github.com/Pure-Storage-Ansible/FlashArray-Collection/pull/177

Simon

| *Simon Dodsley MBCS CITP* |  Technical Director, New Stack
| Global Cloud Architecture Organization
| Pure Storage, Inc. | +1 (510) 516-2682
| ***@***.*** | www.purestorage.com

[image: http://www.purestorage.com/_media/header_logo.png?130529]

**Comment by RomainDusi** [comment]
Hello,

I've recently updated to version 1.8.0 of the Purestorage Collection and still got the same error when creating a new volume (this doesn't occur when modifying an existing volume).

Please see attached the error log.

[Error2.log.txt](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/6413845/Error2.log.txt)

Ansible 3.2.0
Purestorage 1.19.0
Py-Pure-Client 1.8.0
Netaddr 0.8.0
Requests 2.25.1
Purestorage.flasharray 1.8.0 (ansible collection)

The bay is using Purity/FA 5.3.15
Also using self-signed certificate

Thank you.

**Comment by sdodsley** [comment]
Please execute this command in a browser and post the output:
`https://<array_mgmt_vip>/api/api_version`

**Comment by RomainDusi** [comment]
Here is the output :

{"version": ["1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10", "1.11", "1.12", "1.13", "1.14", "1.15", "1.16", "1.17", "1.18", "2.0", "2.1"]}

**Comment by sdodsley** [comment]
What sort of pod is this?

**Comment by RomainDusi** [comment]
I'm sorry i did not understand your question.

What do you mean "what sort of pod" ?
I've Check the `https://<array_mgmt_vip>/api/api_version` on the Purestorage Bay we are using for testing.

**Comment by sdodsley** [comment]
no problem. I see the issue - there is a mismatch of API version checking in the code.
Can you change line 279 in `purefa_volume.py` to read
`PROMOTE_API_VERSION = "1.19"`
This should fix the problem.
If you confirm this resolves the issue we will create a PR to fix thid.

**Comment by RomainDusi** [comment]
Ok thank you, it did resolve the issue !
