### ISSUE TITLE
Add volume in Protection group when creating the volume

### ISSUE THREAD

**Issue by RomainDusi** [Pure-Storage-Ansible/FlashArray-Collection#178]
**Is your feature request related to a problem? Please describe.**
Hi, when creating a new volume using purefa_volume, there is no parameter to add the volume to a protection group.
We couln't find any parameter to move a volume to a protection group.

**Describe the solution you'd like**
Adding a new parameter to the purefa_volume module allowing us to set the volume protection group at creation or modification.

**Additional context**
Request from Storage Service at Groupama (G2S).

**Comment by sdodsley** [comment]
To add a volume to a Protection Group you use the `purefa_pg` module.
We will look into adding a `pg` option to the `purefa_volume` in the future.

**Comment by RomainDusi** [comment]
Hi,

We have found that possibility but encountered some troubles.

Playbook :
- name: Create protection group and place the volume
    purefa_pg:
      pgroup: "{{purefa_pgroup}}"
      volume:
       - "{{purefa_pod_name}}::{{purefa_volume_name}}"
      fa_url: "{{purefa_url}}"
      api_token: "{{purefa_api_token}}"

I then start my playbook with an existing volume named "volume01" and everythin works just fine, new Protection group and our volume in it.
But if later that day i decide te create an other volume "volume02" and re-start the script, only "volume02" is present in the Protection Group.

Is there a way to just add a volume to the protection group or do we need to recreatethe pg and list every volumes each time ?

Thank you.

**Comment by sdodsley** [comment]
You have to list all volume in the protection group.
I see your issue and am working on a solution.

**Comment by sdodsley** [comment]
Addressed in #182 
Please check to see if this does what you need.

**Comment by GillesTrouche** [comment]
Hello @sdodsley  I work with @RomainDusi  I think it is exactly what we need.

**Comment by sdodsley** [comment]
Closing this as the customer appears happy with the provided solution.
