### ISSUE TITLE
Unable to move a volume to a volume group. 

### ISSUE THREAD

**Issue by jerinkumar** [Pure-Storage-Ansible/FlashArray-Collection#190]
I am receving the following error when I try to move a volume to a volume group.

UnboundLocalError: local variable 'target_exists' referenced before assignment

The following is the playbook that I used for this. Both the volume and volume group exist in the array.

  tasks:
   - name: Move Volume to a volume group
     purefa_volume:
       name: ansibletest1_lun_1
       move: ansibletest1
       fa_url: "{{ fa_url }}"
       api_token: "{{ fa_api }}"
     register: output
   - name: Diaplay output
     debug: msg="{{ output }}"

[error message.txt](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/6387139/error.message.txt)

**Comment by sdodsley** [comment]
Hi - please can you confirm which Collection version you are using for FlashArray and the version of Ansible.
If you could also provide the output of the failure when using `-vvvv` with the `ansible-playbook` command

**Comment by jerinkumar** [comment]
Thank you.

Please find below the details and the output attached.

ansible-galaxy 2.9.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/local/<uid>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]


[error message vvvv.txt](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/6387460/error.message.vvvv.txt)

**Comment by sdodsley** [comment]
It appears you may not be using the latest version of the Collections.

Please run `ansible-galaxy collection install purestorage.flasharray --force` and retry.

**Comment by jerinkumar** [comment]
Thank you. It works perfectly after upgrading to the latest  purestorage.flasharray collection.

Appreciate your help on this.
