### ISSUE TITLE
Unable to clear an existing Volume Group BW_QOS setting.

### ISSUE THREAD

**Issue by jerinkumar** [Pure-Storage-Ansible/FlashArray-Collection#191]
Hi,

When I try to clear an existing bw_qos setting it throws an error "fatal: [localhost]: FAILED! => {"changed": false, "msg": "Vgroup test2 Bandwidth QoS removal failed."}"

Please find below the play and I have attached the detailed error message. Please check.

  tasks:
   - name: Create volume group
     purefa_vg:
       name: test2
       bw_qos: 0
       fa_url: "{{ fa_url }}"
       api_token: "{{ fa_api }}"
     register: vol_output
   - name: Diaplay output
     debug: msg="{{ vol_output }}"

[bw_qos_error message.txt](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/6392978/bw_qos_error.message.txt)

**Comment by sdodsley** [comment]
Please confirm the following information:

FlashArray Purity Version:
Ansible Version:
Ansible FlashArray Collection Version:

**Comment by sdodsley** [comment]
We are testing #194  to resolve this bug.
This will be included in the next Collections release. In the interim, you can use this PR to get the updated code.

**Comment by jerinkumar** [comment]
Thank you. I am using the latest collection 

> Please confirm the following information:
> 
> FlashArray Purity Version:
> Ansible Version:
> Ansible FlashArray Collection Version:

I am using the latest collection. Unable to get the exact version because my ansible-galaxy is not supporting the collections list command. Please find the other details below.

purity - 5.3.15
Ansible - 2.9.17

**Comment by sdodsley** [comment]
Fixed in #194
