### ISSUE TITLE
Creating a host with a duplicate wwn. Host is created without wwn.

### ISSUE THREAD

**Issue by BenGaba** [Pure-Storage-Ansible/FlashArray-Collection#192]
**Is your feature request related to a problem? Please describe.**
When creating a new host with Purefa_host with duplicates WWNs ( associated with an other host), the host is still created without WWNs.

**Describe the solution you'd like**
Doing a full rollback. Do not create the host.

**Describe alternatives you've considered**

**Additional context**

**Comment by sdodsley** [comment]
Can you please supply the following information please to assist with resolving this:

FlashArray Purity Version:
Ansible Version:
Ansible FlashArray Collections Version:

**Comment by BenGaba** [comment]
Hello,
Please find the information below :  

FlashArray Purity Version: 5.3.15
Ansible Version: 2.10.7
Ansible FlashArray Collections Version: 1.6.1

**Comment by sdodsley** [comment]
We are testing #193 to resolve this bug.
This will be included in the next Collections release. In the interim, you can use this PR to get the updated code.
Additionally, we suggest you upgrade your FlashArray Collections to the latest version using the command
`ansible-galaxy collection install purestorage.flasharray --force`

**Comment by BenGaba** [comment]
Thank you

**Comment by sdodsley** [comment]
Fixed in #193
