### ISSUE TITLE
Choose FC network ports and change there status

### ISSUE THREAD

**Issue by SchmidtJonathan1** [Pure-Storage-Ansible/FlashArray-Collection#198]
Hello,
its not possible to choose FC network ports and change there status, like enable port. I tried to write it in small letter and big letter no chance....

Every time i want to choose the ports runs at an error message:
Invalid network interface specified

![image](https://user-images.githubusercontent.com/78372510/117309905-2a62d100-ae83-11eb-9665-fcbb3fda66bb.png)

![image](https://user-images.githubusercontent.com/78372510/117309936-3058b200-ae83-11eb-8cd9-1d0d4b6dfc09.png)

**Comment by sdodsley** [comment]
Fibre Channel ports are not network interfaces and the `purefa_network` module only works with network interfaces.
There is no way to disable FC ports in Purity, therefore there is no Ansible module to perform this task.

**Comment by SchmidtJonathan1** [comment]
Hello simon,
what you mean with your answer?  Purity Version 6.1.5
![image](https://user-images.githubusercontent.com/78372510/117437109-11fcc000-af30-11eb-97f1-cce4a3c773d3.png)

**Comment by sdodsley** [comment]
OK - New feature in 6.1.5 I was unaware of... I'll get a PR raised to get this resolved.

**Comment by sdodsley** [comment]
PR #199 should resolve your issue.
Please try this out and let us know...

**Comment by SchmidtJonathan1** [comment]
Hello Simon, 
sorry for my late reply.
i will test it today in the afternoon or tomorrow.

**Comment by SchmidtJonathan1** [comment]
Hello Simon,
i got a SSL error code...

"/var/lib/awx/venv/ansible/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1620742267.679754-194324580680132/AnsiballZ_purefa_network.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1620742267.679754-194324580680132/AnsiballZ_purefa_network.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1620742267.679754-194324580680132/AnsiballZ_purefa_network.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_network', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_purestorage.flasharray.purefa_network_payload_6gh4ctk2/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py\", line 333, in <module>\n  File \"/tmp/ansible_purestorage.flasharray.purefa_network_payload_6gh4ctk2/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py\", line 314, in main\n  File \"/tmp/ansible_purestorage.flasharray.purefa_network_payload_6gh4ctk2/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/module_utils/purefa.py\", line 117, in get_array\n  File \"/usr/local/lib/python3.6/site-packages/pypureclient/flasharray/client.py\", line 73, in Client\n    validate_version(array_versions, version)\n  File \"/usr/local/lib/python3.6/site-packages/pypureclient/flasharray/client.py\", line 96, in validate_version\n    raise ValueError(msg.format(version))\nValueError: version 2.5 not supported by client.\n",

**Comment by sdodsley** [comment]
Hi - you need to upgrade the pypureclient SDK module to the latest version
to support the REST API version on your array.

| *Simon Dodsley MBCS CITP* |  Technical Director, New Stack
| Global Cloud Architecture Organization
| Pure Storage, Inc. | +1 (510) 516-2682
| ***@***.*** | www.purestorage.com

*BOOK TIME WITH ME*: 30 minutes
<https://purestorage.chilipiper.com/book/me/simon-dodsley?type=my-meeting>

[image: http://www.purestorage.com/_media/header_logo.png?130529]

**Comment by sdodsley** [comment]
This fix will be included in the next release of the FlashArray Collections
