### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by abadger** [Pure-Storage-Ansible/FlashArray-Collection#22]
**Describe the bug**
I was testing some code I have that works with collections and was happy to find you had a collection to test against :-)  When I was using it, though, I found a discrepancy as to what license the collection is under.

* In the README.md I see BSD-2-clause: https://github.com/Pure-Storage-Ansible/FlashArray-Collection/blob/master/collections/ansible_collections/purestorage/flasharray/README.md
* Toplevel LICENSE file is BSD-2-clause: https://github.com/Pure-Storage-Ansible/FlashArray-Collection/blob/master/LICENSE
* In the module_utils code is BSD-2-clause: https://github.com/Pure-Storage-Ansible/FlashArray-Collection/blob/master/collections/ansible_collections/purestorage/flasharray/plugins/module_utils/purefa.py

* The license in the galaxy metadata is GPLv2 or later: https://github.com/Pure-Storage-Ansible/FlashArray-Collection/blob/master/collections/ansible_collections/purestorage/flasharray/galaxy.yml

* The license in all of the modules is GPLv3 or later: (Example, one of many: https://github.com/Pure-Storage-Ansible/FlashArray-Collection/blob/master/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_alert.py#L5 )

**To Reproduce**
1. Search the files listed in the problem description for "license"

**Expected behavior**

Licenses in the files and metadata to agree.  no extraneous licenses present in the metadata.

**Additional context**

I think the solution to this is the following:

* Add GPLv3 or later to the README.md
* Add a copy of the GPLv3 in a COPYING file in the toplevel of the github repo
* In the galaxy.yml file, the license metadata is a list so I think you can:
  * Remove gpl-2.0-or-later
  * Add gpl-3.0-or-later
  * Add bsd-2-clause

**Comment by sdodsley** [comment]
Documentation changes added
