### ISSUE TITLE
purefa_host can't create host with any capitol letters

### ISSUE THREAD

**Issue by nurseandthenerd** [Pure-Storage-Ansible/FlashArray-Collection#240]
**Describe the bug**
all hosts are created with lower case letters regardless of how it was specified.

**To Reproduce**
- name: Create host 
  purestorage.flasharray.purefa_host:
    name: "Test-T01"
    wwns:
      - 20:00:00:25:B5:38:A0:02
      - 20:00:00:25:B5:38:B0:02
    fa_url: "{{storagearray.fqdn}}"
    api_token: "{{token.json.api_token}}"

**Expected behavior**

host Test-T01 created. instead test-t01 is created.

**Screenshots**

![image](https://user-images.githubusercontent.com/36507780/139708426-4b8492c5-ddf5-4ef4-9922-3282064ce277.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Version [e.g. 22] 20.04

**Additional context**
believe the problem to be on line 864 of purefa_host.py. "module.params["name"] = module.params["name"].lower()" this appears to be setting all input for the name of the host to be lower case.

**Comment by nurseandthenerd** [comment]
That makes sense, but you can create a host with capitol letters from the GUI. It would be great if the ansible modules supported the same. I saw that the functions to check for a host checked for everything as lower case, to ensure the Host1 and host1 issue doesn't happen, but i didn't realize creating one was forced to lower.

**Comment by sdodsley** [comment]
This issue is that there are many modules that use the hostname and they all have to understand the case. There are a lot of checks done as well that different cases break, hence why we force to lowercase.
I might be wrong but I think our best practices might mention using lowercase as a preference.
I will add a note to the Ansible Collections docs that kebab-case is used by Purity for hosts, volumes, etc

**Comment by sdodsley** [comment]
#241

**Comment by nurseandthenerd** [comment]
the purefa_volume and the purefa_hg module both worked with upper case letters. the only only one that didn't was the _host module. This was one of the reasons i thought it was a bug. does this also mean that the host module can't modify any host containing upper case letters?

**Comment by nurseandthenerd** [comment]
nevermind. it can update hosts with capital. I'll go ahead and close this issue. I'm using the ansible uri module to create the host and then this module to update that host.

**Comment by sdodsley** [comment]
Let me look at the logic being used across the modules and see what can be done to solve this in the long term

**Comment by nurseandthenerd** [comment]
Awesome. thank you!

**Comment by michkosa** [comment]
Hello @nurseandthenerd ,
I saw that you operate a Cisco m9250 and I have a question about its operation. Could you please contact me at mich.k@seznam.cz? Thank you.
