### ISSUE TITLE
Skip overwrite bind_password in purefa_ds module

### ISSUE THREAD

**Issue by sanderdescamps** [Pure-Storage-Ansible/FlashArray-Collection#291]
**Is your feature request related to a problem? Please describe.**
I automated the configuration of all our Pure storage servers via Ansible. Everything has been integrated in a ci pipeline and it works perfectly. Before Ansible actually performs the change, Ansible is first ran with the `--check` flag to see which changes will be applied. The problem is that the `purefa_ds` module always registers a change. Even when there is no change.
The change is triggered by the bind_password. Because Ansible can't verify if it has changed or not so it always overrides the current password. 

**Describe the solution you'd like**
Option 1: Ignore the `bind_password` when there are no other changes to the directory service. By adding a new property (ex. `force_password_reset`) this behavior could be overwritten. 

Option 2: Adding an option `skip_password_override` which prevents Ansible from updating the password when there are no other changes to the directory service. 

**Additional context**
I'm wondering what Pure thinks about this feature and would like to know which option they prefer. I can allocate some time to implement this change myself and create a pull request for it. But preferably after I know for which option I need to chose.

**Comment by sdodsley** [comment]
@sanderdescamps can you check out #292 to see if this resolves your issue and let us know

**Comment by sanderdescamps** [comment]
I'm sorry for the delay. I just tested the code and replied to the [Merge Request](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/pull/292#issuecomment-1140877346). 

A huge thank you at @sdodsley for the rapid response.

**Comment by sdodsley** [comment]
Fixed with #292
