### ISSUE TITLE
purefa_hg is not idempotent for volume disconnects

### ISSUE THREAD

**Issue by StephenEGibson** [Pure-Storage-Ansible/FlashArray-Collection#309]
**Describe the bug**
purefa_hg is not idempotent specifically with volume disconnects. If you try to disconnect a volume that is already disconnected the task will error out.

**To Reproduce**
1. Remove a volume from a host group
2. Attempt to remove the same volume again from the host group

**Steps:**

    - name: Create a Volume
      purestorage.flasharray.purefa_volume:
        api_token: "{{ token }}"
        fa_url: "{{ url }}"
        name: "test-vol"
        size: "1G"
        state: "present" 
  
    - name: Create a FC Host
      purestorage.flasharray.purefa_host:
        api_token: "{{ token }}"
        fa_url: "{{ url }}"
        name: "test-host"
        protocol: "fc"
        personality: "esxi"
        wwns: 
          - "10:00:00:00:00:00:00:01"
        state: "present" 
  
    - name: Create a Host Group
      purestorage.flasharray.purefa_hg:
        api_token: "{{ token }}"
        fa_url: "{{ url }}"
        hostgroup: "test-hg"
        host: "test-host"
        state: "present"
  
    - name: Connect Volume to Host Group
      purestorage.flasharray.purefa_hg:
        api_token: "{{ token }}"
        fa_url: "{{ url }}"
        hostgroup: "test-hg"
        volume: "test-vol" 
        state: "present" 
  
    - name: Disconnect Volume from Host Group
      purestorage.flasharray.purefa_hg:
        api_token: "{{ token }}"
        fa_url: "{{ url }}"
        hostgroup: "test-hg"
        volume: "test-vol" 
        state: "absent" 
  
    - name: Disconnect Volume from Host Group
      purestorage.flasharray.purefa_hg:
        api_token: "{{ token }}"
        fa_url: "{{ url }}"
        hostgroup: "test-hg"
        volume: "test-vol" 
        state: "absent" 
  
**Result**

TASK [Disconnect Volume to Host Group] ****************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to disconnect volume test-vol from hostgroup test-hg"}

**Expected behavior**
If the volume is already disconnected it should show as OK (unchanged) and not fail out.

**Additional context**
I'm writing a failover playbook. In the event something breaks in the middle I would like the users to have the ability to kick-off the playbook again.

**Comment by sdodsley** [comment]
@StephenEGibson can you please check whether this patch resolves your bug.

**Comment by StephenEGibson** [comment]
That appears to have resolved the issue. Thanks Simon!

**Comment by StephenEGibson** [comment]
Re-opening this as once I integrated it into the failover workflow the volume deletes started failing because the volumes weren't disconnected. Switching back to the prior version restored functionality. Can you double-check that volumes are getting disconnected on the array after this update?
