### ISSUE TITLE
python >= '3.3' in requirements.txt can't be satisfied in Redhat ubi8-python39 container

### ISSUE THREAD

**Issue by davidstanaway** [Pure-Storage-Ansible/FlashArray-Collection#332]
**Describe the bug**
I am running ansible in a registry.access.redhat.com/ubi8/python-39 podman image 
and the requirements file for the purestorage.flasharray cannot be satisfied

**To Reproduce**
Dockerfile

FROM registry.access.redhat.com/ubi8/python-39

USER 0

RUN python -m pip install --upgrade pip; \
    python -m pip install --upgrade virtualenv; \
    python -m pip install ansible; \
    ansible-galaxy collection install purestorage.flasharray; \
    python -m pip install -r ~/.ansible/collections/ansible_collections/purestorage/flasharray/requirements.txt

CMD bash --login

Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[root@743b203eb084 ~]# python --version
Python 3.9.7

Starting collection install process
Downloading https://galaxy.ansible.com/download/purestorage-flasharray-1.14.0.tar.gz to /opt/app-root/src/.ansible/tmp/ansible-local-26_erde4it/tmp6qttt7mq/purestorage-flasharray-1.14.0-lwa4i85o
Installing 'purestorage.flasharray:1.14.0' to '/opt/app-root/src/.ansible/collections/ansible_collections/purestorage/flasharray'
purestorage.flasharray:1.14.0 was installed successfully
Collecting purestorage>='1.19'
  Downloading purestorage-1.19.0.tar.gz (28 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting py-pure-client>='1.27'
  Downloading py-pure-client-1.28.0.tar.gz (5.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 91.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting netaddr
  Downloading netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 115.8 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 134.1 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement python>='3.3' (from versions: none)
ERROR: No matching distribution found for python>='3.3'

**Expected behavior**
Expect to be able to install this collection with Python 3.9

**Comment by davidstanaway** [comment]
Possibly related:

  DEPRECATION: purestorage is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for purestorage: started
  Running setup.py install for purestorage: finished with status 'done'
  DEPRECATION: py-pure-client is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for py-pure-client: started

**Comment by sdodsley** [comment]
The `requirements.txt` has been updated to remove unnecessary entries
