### ISSUE TITLE
purestorage.flasharray.purefa_network module doesn't support FC Replication

### ISSUE THREAD

**Issue by jgargs** [Pure-Storage-Ansible/FlashArray-Collection#335]
Using the CLI you can set the replication attribute for a FC port using the following command. 
purenetwork fc setattr --servicelist replication ct0.fc8 ct0.fc9 ct1.fc8 ct1.fc9

It would be nice to be able to set the replication attribute on FC ports via Ansible. To be able to pass the FC port and the replication attribute into the purestorage.flasharray.purefa_network module to accomplish the same thing as the CLI command. 

I had looked through all the modules listed for FlashArray and did not find a way to do this via Anisble.
https://docs.ansible.com/ansible/latest/collections/purestorage/flasharray/index.html

**Comment by sdodsley** [comment]
@jgargs please try PR #336 to see if this resolves your issue,

**Comment by jgargs** [comment]
@sdodsley Thanks! That appears to be working for us.
