### ISSUE TITLE
purefa_network fails when servicelist is not defined

### ISSUE THREAD

**Issue by sanderdescamps** [Pure-Storage-Ansible/FlashArray-Collection#339]
**Describe the bug**
purefa_network fails when servicelist is not defined. 

https://github.com/Pure-Storage-Ansible/FlashArray-Collection/blob/831268f22ce7f049f07c94c2f7839d1fa95692b1/plugins/modules/purefa_network.py#L399

Before checking if `system` is in the list, `module.params["servicelist"]` need to be checked isn't `None`.

**Comment by sdodsley** [comment]
Good catch. Fixed by #340 .
Please confirm this resolves your issue
