### ISSUE TITLE
Truncated output when changing size of volume

### ISSUE THREAD

**Issue by smutel** [Pure-Storage-Ansible/FlashArray-Collection#359]
**Describe the bug**
The output of purestorage.flasharray.purefa_volume contains less details when changing volume size than when creating volume.

**To Reproduce**
1. Create a volume of 1G with this collection
2. The volume dict inside the output contains created/name/promotion_status/requested_promotion_state/serial/size/source
3. Increase the volume size to 2G with this collection
4. The volume dict inside the output contains name and size only

**Expected behavior**
The volume dict returned by the collection should be the same for creation or update.

**Comment by sdodsley** [comment]
@smutel the original thinking behind this ws to only expose what has changed, therefore all the detailed information on a volume is only provided at creation time. Changes will only give the deltas.
We can certainly look to enhancing the response dict for all updates to include all information. Leve this with us and w'll comment here when we have a solution.

**Comment by smutel** [comment]
I understand that you don't want to expose to much information. However when there is no change we have creation/name/promotion_status/requested_promotion_state/serial/size/source. So having only name/size when the size has changed is strange. For our needs we need at least creation/serial.

**Comment by sdodsley** [comment]
@smutel if you would like to try the linked path (#384) this will resolve your issue we beleive.
