### ISSUE TITLE
Requesting purefa_network support for bond / lacp / virtual interfaces

### ISSUE THREAD

**Issue by dbuenoparedes** [Pure-Storage-Ansible/FlashArray-Collection#391]
**Describe the solution you'd like**
Equivalent configuration option to match the CLI commands:
`purenetwork eth create lacpbond [--subinterfacelist SUBINTERFACELIST] INTERFACE`
`purenetwork eth create vif [--address ADDRESS] { --subnet SUBNET | --subinterfacelist SUBINTERFACELIST } INTERFACE...`

**Additional context**
There are currently no options under the **purefa_network** module to fully configure these type of interfaces. There is a way to specify a vif interface but only with `address` attribute and not `subnet` nor `subinterfacelist`.

**Comment by sdodsley** [comment]
You are correct. 
We'll look at fixing this in the `purefa_vif` module and see about creating a `purefa_lacp` module the next collection release.

**Comment by dbuenoparedes** [comment]
Hi @sdodsley, is this still being considered for development? Thanks!

**Comment by sdodsley** [comment]
@dbuenoparedes yes - this is still in consideration

**Comment by tylergmuir** [comment]
@sdodsley I also have a need for the subinterface functionality. It seems like to fully implement it we would want to add a sub interface list parameter to both purefa_network and purefa_vlan. 

I don't have a current use case for the lacp piece, but if the above plan sounds in line with what you were thinking I can at least help contribute to this enhancement.

**Comment by sdodsley** [comment]
@tylergmuir @dbuenoparedes I am going to start work on the `create vif` portion of this today

**Comment by sdodsley** [comment]
@tylergmuir @dbuenoparedes #474 now covers the creation of VIF and LACP interfaces as well as assigning subinterfaces/subordinates and subnet.
