### ISSUE TITLE
How to get pureaudit list output with Ansible 

### ISSUE THREAD

**Issue by colinet** [Pure-Storage-Ansible/FlashArray-Collection#400]
Hello,

We want to control changes performed on Pure storage arrays using Ansible.
How can we get pureaudit list output with Ansible ?

Rgds

**Comment by sdodsley** [comment]
@colinet That currently isn't available. I will add it for the next release, but will let you know when the code is ready so you can try it early.

**Comment by colinet** [comment]
This is a good news.
I will test it for sure.

Thx a lot.

**Comment by sdodsley** [comment]
@colinet See #402. This should give you what you need.

**Comment by sdodsley** [comment]
Added to Release 1.19.0

**Comment by colinet** [comment]
Thx a lot.  :-)
