### ISSUE TITLE
purefa_certs is not taking care of change in state:sign

### ISSUE THREAD

**Issue by pda79** [Pure-Storage-Ansible/FlashArray-Collection#430]
when you use purefa_certs and you decide to change  a parameter, the previous conf is used 
this is the case for all parameter of sign request (common_name, country, email, locality, province, organization, org_unit)

**To Reproduce**
use 
purefa_certs:
state: sign
org_unit: "new_org_unit"

**Expected behavior**
a signing request with the good parameter

**Additional context**
purestorage                        1.19.0
py-pure-client                     1.33.1

**Comment by sdodsley** [comment]
@pda79 please try PR #433 to see if this resolves your issue and let me know.

**Comment by pda79** [comment]
@sdodsley  i have made a try but  it seems that  it works worse.
take a look at thit screenshot
![2023-07-28 11_20_36-Clipboard](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/assets/25984812/23de7058-36b2-4184-9905-a41995921158)

**Comment by sdodsley** [comment]
@pda79 OK - will fix that and get a new update later today

**Comment by sdodsley** [comment]
@pda79 Please try this new verson

**Comment by pda79** [comment]
@sdodsley  this new version is working
but with this new version  i have found another bug in this use case:
purefa_certs:
generate: true
![2023-07-28 16_04_59-2023-07-28 15_59_48-PWVD1410 - Poste de DEV Windows - Desktop Viewer](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/assets/25984812/3b1eb76a-1573-4148-840b-d821594899f3)

**Comment by sdodsley** [comment]
@pda79 give the latest a try - hopefully this catches everything now

**Comment by pda79** [comment]
@sdodsley great all is working fine.  Good job and welle done. Thanks a lot

**Comment by sdodsley** [comment]
No problem. Thank you for finding the problem.
