### ISSUE TITLE
remove an gateway address from a interface

### ISSUE THREAD

**Issue by ryuyamag** [Pure-Storage-Ansible/FlashArray-Collection#449]
My customer tried to delete a gateway for an interface, but was unable to delete just the gateway.
When I checked, I found that in order to delete the gateway, it also needed to clear the address.
It would be helpful if there was a way to delete the gateway without clearing the address.

**Comment by sdodsley** [comment]
Please provide the following details:

* Ansible version
* FlashArray Collection version
* Purity version
* FlashArray module causing the failure
* Name of the interface and the service(s) enabled on the interface
* An example task that fails
* Response from `ansible-playbook -vvvv` when running a failing task

**Comment by ryuyamag** [comment]
Hello Team,

 

Thank you for respoinding to this feature request.

 

•             Ansible version: ansible [core 2.15.4]

•             FlashArray Collection version: 1.21.0

•             Purity version: 6.3.13

•             FlashArray module causing the failure: purefa_network

•             Name of the interface and the service(s) enabled on the interface: ct0.eth4

•             An example task that fails

•             Response from ansible-playbook -vvvv when running a failing task: see attached file

 

Thanks,

**Comment by sdodsley** [comment]
@ryuyamag You caan't attach a file via email to an issue. You need to include all the file as text, or provide a link to a location where the file can be seen.

You also have not provided the information on which services are enabled on the port where the gateway is wanting to be removed.

**Comment by ryuyamag** [comment]
[purefa_network.log](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12714288/purefa_network.log)
Sorry I didn't know. Thanks.

also, ct0.eth4 provides iSCSI Service.

**Comment by ryuyamag** [comment]
Thank you for your prompt response to this feature request. 
I have confirmed that the functionality has been added.
