### ISSUE TITLE
Seems that purefa_pg does not accept ActiveCluster volumes?

### ISSUE THREAD

**Issue by dnix101** [Pure-Storage-Ansible/FlashArray-Collection#45]
**Is your feature request related to a problem? Please describe.**
Seems that when you use the purefa_pg module, your not able to add ActiveCluster volumes to the protection group. Regular volumes are accepted

**Describe the solution you'd like**
Add support for adding/removing ActiveCluster volumes to a protection group.

**Describe alternatives you've considered**
None

**Additional context**
No additional context

**Comment by sdodsley** [comment]
I think you will find AC volumes are not supported in PGs at the moment. You can't do this from the GUI either...

**Comment by sdodsley** [comment]
Not a thing...
