### ISSUE TITLE
cannot create a remote snapshot on offload array

### ISSUE THREAD

**Issue by ryuyamag** [Pure-Storage-Ansible/FlashArray-Collection#451]
It seems it cannot create remote snapshots in 1.21. I confirmed that it works in 1.20.

•	Ansible version: ansible [core 2.15.4]
•	FlashArray Collection version: 1.21.0
•	Purity version: 6.3.13
•	FlashArray module causing the failure: purefa_snap
•	An example task that fails:  Create a remote volume snapshot on offload device arrayB
•	Response from ansible-playbook -vvvv when running a failing task: see attached file
[purefa_snap.log](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12722253/purefa_snap.log)

**Comment by sdodsley** [comment]
Yes - this is definately a bug.
We will get that fixed as soon as possible

**Comment by sdodsley** [comment]
@ryuyamag please try the patch and let us know if this fixes your issue

**Comment by ryuyamag** [comment]
This patch worked fine!
Thank you for fixing this.
