### ISSUE TITLE
purefa_pgsched errors out with a KeyError: 'replicate_enabled'

### ISSUE THREAD

**Issue by StephenEGibson** [Pure-Storage-Ansible/FlashArray-Collection#453]
**Describe the bug**
pgsched fails with a KeyError: 'replicate_enabled'. It occurs regardless of the enabled parameter. 

**To Reproduce**
    - name: Set Target Retention on Protection Group
      purestorage.flasharray.purefa_pgsched:
        api_token: "{{ api_token }}"
        fa_url: "{{ fa_url }}"
        name: "{{ pg_name }}"
        schedule: "replication"
        target_per_day: 1
        target_days: 1
        target_all_for: 7200

**Expected behavior**
The Protection Group is enabled with the desired replication schedule.

**Desktop (please complete the following information):**
 - Version 
    -  purestorage.flasharray 1.21.0
    -  python 3.10.7
    -  ansible core 2.14.2
    -  purity 6.4.10

**Comment by sdodsley** [comment]
@StephenEGibson no worries - I found the problem. Please check if #454 resolves your issue.

**Comment by StephenEGibson** [comment]
That appears to have resolved it. Thanks!
