### ISSUE TITLE
purefa_info fails when gather subset includes 'alerts' In new purefa_info.py fix for issue 447

### ISSUE THREAD

**Issue by samuellay** [Pure-Storage-Ansible/FlashArray-Collection#467]
**purefa_info fails when gather subset includes 'alerts'**
In new purefa_info.py fix for issue 447

**To Reproduce**
`
- name: Collect the array information
  purestorage.flasharray.purefa_info:
    gather_subset:
      - alerts
    fa_url: "{{ ansible_host }}"
    api_token: "{{ api_token }}"
  register: array_info
  when: api_token is defined and api_token
  no_log: false
`

**Error**
`fatal: [pur09p99st001]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "fa_url": "pur09p99st001",
            "gather_subset": [
                "alerts"
            ]
        }
    },
    "msg": "value must gather_subset must be one or more of: all,minimum,config,performance,capacity,network,subnet,interfaces,hgroups,pgroups,hosts,admins,volumes,snapshots,pods,replication,vgroups,offload,apps,arrays,certs,kmip,clients,policies,dir_snaps,filesystems,virtual_machines,hosts_balance,subscriptions, got: alerts"
}
`

**Comment by sdodsley** [comment]
Fixed in #448
