### ISSUE TITLE
unable to update network interface with no IP address set

### ISSUE THREAD

**Issue by tylergmuir** [Pure-Storage-Ansible/FlashArray-Collection#472]
**Describe the bug**
When you have an interface that you want to update without an IP address set, say in the case you are changing the services. The purefa_network module fails with an error that state "failed to detect a valid IP". A workaround is to set the address to `0.0.0.0/0` but this results in the module reporting `changed` every time.

**To Reproduce**
1. Have an interface that doesn't have an IP address set. 
2. Attempt to set only the services and/or MTU of the interface and do not specify the `address` or `gateway` parameters.

**Expected behavior**
The expected behavior is that the network interface would be updated as it is a valid state to have no address assigned.

**Comment by sdodsley** [comment]
@tylergmuir Try #471 to see if that has helped.

**Comment by tylergmuir** [comment]
@sdodsley #471 does fix this issue.

**Comment by sdodsley** [comment]
@tylergmuir purefa_network changes backed out of this change and moved to #474
