### ISSUE TITLE
network port reports as changed when removing the address or gateway

### ISSUE THREAD

**Issue by tylergmuir** [Pure-Storage-Ansible/FlashArray-Collection#473]
**Describe the bug**
When using `purefa_network`, if you have `address` set to `0.0.0.0/0` or `gateway` set to 0.0.0.0 to remove either of those configurations from the network on the array, it always reports back `changed` regardless of if anything was changed.

**To Reproduce**
1. Have a network port without an IP address or gateway configured.
2. Use the `purefa_network` module with `state: present`, `address: 0.0.0.0/0`, and `gateway: 0.0.0.0`.

**Expected behavior**
The expected behavior is that if nothing on the port is changed, the status should report `ok` instead of `changed`.

**Comment by tylergmuir** [comment]
@sdodsley I noticed this issue a few days ago. I think it should be a pretty easy fix to just check for `0.0.0.0/0` or `0.0.0.0` and see if the existing state is `None` on the two options. It could be rolled into #471 if you wanted or it can be done separately but I was going to hold off on submitting a PR for this since you already have one inflight for that module.

**Comment by sdodsley** [comment]
@tylergmuir I'll roll it into the work I'm doing for VIF and LACP

**Comment by sdodsley** [comment]
@tylergmuir addressed in #474

**Comment by tylergmuir** [comment]
@sdodsley It looks like it is reporting right now. But I just tested updating an existing `vif` interface and that is failing. I am collecting some more info on why it is failing now.
