### ISSUE TITLE
Minor error in README.md

### ISSUE THREAD

**Issue by samuellay** [Pure-Storage-Ansible/FlashArray-Collection#475]
**Description**
I know this is very picky but . . . .

The README.md file states:

> The Pure Storage Ansible modules force all host and volume names to
use kebab-case.  Any parameters that use camelCase or PascalCase will
be lowercased to ensure consistency across all modules.

We use snake-case for all identifiers except where not allowed by the array.
The array and module only allow dashes (kebob-case) for pod names.  But
is does allow underscores (snake-case) in volume names.  Then there is the
double-colon that is part of the volume name when the volume is in a pod.
Underscores are not allowed in host names.

So, the statement regarding the kebob-case constraint is a little bit off.

**Comment by sdodsley** [comment]
Yes - that was written before we removed support for Python 2.7 in the Collection.
I'll fix it for the next release.
