### ISSUE TITLE
Replication issue with purefa_pgsnap

### ISSUE THREAD

**Issue by ryuyamag** [Pure-Storage-Ansible/FlashArray-Collection#478]
If I set "now:true" and "remote:false" in purefa_pgsnap, replication will not be performed for the created snapshot.
If both are true, it works fine.

The description of "remote" is below, if this param is "false", I think that replication task will queued and replicate later.
> Force immeadiate snapshot to remote targets
> Choices:
>   false ← (default)
>   true

• Ansible version: ansible [core 2.15.4]
• FlashArray Collection version: 1.21.0
• Purity version: 6.3.13
• FlashArray module causing the failure: purefa_pgsnap
• Response from ansible-playbook -vvvv when running a failing task: see attached file
[20231012.zip](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12881864/20231012.zip)

**Comment by sdodsley** [comment]
I'm not sure I understand your issue really, but I think I found a bug.
Please see if #483 resolves your issue.
If not please give a more detailed description of what you think should happen for each combination of `now` and `remote`.

**Comment by ryuyamag** [comment]
I'm sorry that I couldn't explain it well.

 

There are 4 types of combinations of "now" and "remote".

 

[1] now:true remote:true

 

[2] now:true remote:false

 

[3] now:false remote:true

 

[4] now:false remote:false

 

Results 1, 3, and 4 work as I expected.

2, like 3 and 4, only a snapshot is created, which is different from what I expected.

2 passes "replicate_now=false" to "array.create_pgroup_snapshot", but shouldn't it pass "replicate=true"?

 

replicate:

If set to true, queues up and begins replicating to each allowed target after all earlier replication sessions for the same protection group have been completed to that target. The replicate and replicate_now parameters cannot be used together.

 

replicate_now:

If set to true, replicates the snapshots to each allowed target. The replicate and replicate_now parameters cannot be used together.
