### ISSUE TITLE
Add VG rename

### ISSUE THREAD

**Issue by colinet** [Pure-Storage-Ansible/FlashArray-Collection#479]
I need to rename volume groups using purefa_vg.
This is possible with CLI but not with Ansible Pure collection.

Could this be added to the collection using purefa_vg command?

**Comment by sdodsley** [comment]
@colinet please try #480 and let me know if it resolves your issue

**Comment by colinet** [comment]
Going to test.

**Comment by sdodsley** [comment]
@colinet sorry for the delay - travelling in the Far East.
Please retry the patch now

**Comment by colinet** [comment]
No pb for the delay. I tested the updated patch 480.
It works as expected. The rename VG was done with the requested name "{{ rename }}".
So this is good for me.

Any hint when this will be available in the collection?

**Comment by sdodsley** [comment]
I think we are looking ot release a new collection next week, or the week after

**Comment by colinet** [comment]
Great! 
Thx !
