### ISSUE TITLE
purefa_pgsched can't set "snap_at" or "replicate_at" to 0

### ISSUE THREAD

**Issue by ryuyamag** [Pure-Storage-Ansible/FlashArray-Collection#481]
There are some cases not possible to update the schedule using purefa_pgsched.
For example, set the schedule in PG as follows
    snap_frequency: 86400
    snap_at: 15:30:00

Then I can't change it to the following settings.
    snap_frequency: 86400
    snap_at: 0

    snap_frequency: 3600
    snap_at: 0
    
• Ansible version: ansible [core 2.15.5]
• FlashArray Collection version: 1.21.0
• Purity version: 6.3.13
• FlashArray module causing the failure: purefa_pgsched

**Comment by sdodsley** [comment]
@ryuyamag can you confirm you are wanting to set the `snap_at` time to be midnight?

**Comment by ryuyamag** [comment]
Thank you for you response.

 

My customer wants to change their schedule from daily to hourly. 

I think that it is necessary to set "snap_at/replicate_at" to 0.

**Comment by sdodsley** [comment]
@ryuyamag Please try #482, but note that if you are changing from a daily schedule to an hourly schedule, there is no requirement to set `snap_at` or `replicate_at` to 0. This is automatically performed by the module.
