### ISSUE TITLE
purefa_info fails when destroyed ProtectionGroup exists

### ISSUE THREAD

**Issue by ryuyamag** [Pure-Storage-Ansible/FlashArray-Collection#493]
For example, if testpg exists in destroyed, it will look like this:
` line 1456, in generate_pgroups_dict\nKeyError: 'testpg'\n",`

•	Ansible version : core 2.15.5
•	FlashArray Collection version: 1.22.0
•	Purity version: 6.3.13
•	FlashArray module causing the failure: purefa_info
•	An example task that fails: pgroups/all
•	Response from ansible-playbook -vvvv when running a failing task:  please see attached
[purefa_info_all.yml.zip](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/13225931/purefa_info_all.yml.zip)

**Comment by sdodsley** [comment]
OK - quick fix here.
I will be putting together a bigger patch to correctly deal with deleted protection groups.
