### ISSUE TITLE
volume is not added with purefa_pg

### ISSUE THREAD

**Issue by ryuyamag** [Pure-Storage-Ansible/FlashArray-Collection#494]
When creating a PG with purefa_pg, the result seems fine.
But when I look at the actual array's PG, the target is set correctly, but the volume is not added to the members of.

```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "enabled": true,
            "eradicate": false,
            "fa_url": "10.229.192.60",
            "host": null,
            "hostgroup": null,
            "name": "testpg1",
            "rename": null,
            "safe_mode": false,
            "state": "present",
            "target": [
                "japan-pslab"
            ],
            "volume": [
                "testvol1"
            ]
        }
    }
}

```

•	Ansible version : core 2.15.5
•	FlashArray Collection version: 1.22.0
•	Purity version: 6.3.13
•	FlashArray module causing the failure: purefa_pg
•	An example task that fails: create new pg
•	Response from ansible-playbook -vvvv when running a failing task: please see attached
[purefa_pg_create.yml.zip](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/13226070/purefa_pg_create.yml.zip)

**Comment by sdodsley** [comment]
@ryuyamag i can't reproduce this error. It works fine for me in my lab.

**Comment by ryuyamag** [comment]
I tried with different version of the array and the results were the same.
I've heard of this happening in customer environments as well. Is there something wrong with our settings?
I attached the additional logs.
[20231102.zip](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/13232970/20231102.zip)

**Comment by sdodsley** [comment]
This is strange - can I get access to the array to see it happening?

**Comment by ryuyamag** [comment]
Yes. I'll send the information separately.
