### ISSUE TITLE
semver violation:   purestorage.flasharray 1.22.0 contains Breaking Changes

### ISSUE THREAD

**Issue by gotmax23** [Pure-Storage-Ansible/FlashArray-Collection#500]
**Describe the bug**

Hi! As part of the ansible community package release process, we've determined that purestorage.flasharray 1.22.0 contains [Breaking Changes](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/blob/master/CHANGELOG.rst#breaking-changes-porting-guide) in violation of Semantic Versioning. The [Versioning and deprecation][1] section of the Collection Requirements requires that collections adhere to Semantic Versioning.

[1]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#versioning-and-deprecation

Until this issue is fixed, ansible package releases will contain 1.21.0, the previous version of this collection without the breaking changes. If the collection maintainers do not respond to this issue within a reasonable amount of time, the collection is subject to [Removal from ansible][2].

 [2]: https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#collections-not-satisfying-the-collection-requirements

**Comment by sdodsley** [comment]
These are not really breaking changes- I believe the `breaking_change` flag was incorrectly used in the changelog fragment. We will fix this and create 1.22.1 to remove the offending flag.
