### ISSUE TITLE
Param enabled not work in purefa_pgsched 

### ISSUE THREAD

**Issue by tpeponas** [Pure-Storage-Ansible/FlashArray-Collection#504]
**Describe the bug**
Module parameter "enabled" not work when is set to false in the module purefa_pgsched.
This parameter is interpreted as boolean , so condition in code: 

_if not module.params["enabled"]:
            snap_enabled = current_snap["snap_enabled"]
        else:
            snap_enabled = module.params["enabled"]_

the condition _if not module.params["enabled"]_ is true when module.params["enabled"] is false, and so pg sched does not change.

This code works to check if parameter "enabled" is defined or not

_if module.params["enabled"] is None:
            snap_enabled = current_snap["snap_enabled"]
        else:
            snap_enabled = module.params["enabled"]_

**Exemple To Reproduce**
- name: Pause PG 
  purestorage.flasharray.purefa_pgsched:
    fa_url: "{{ array }}"
    api_token: "{{ api_token }}"
    name: "{{ pg_name }}"
    schedule: replication
    enabled: false
    state: present
  register: pause_pg

Regards,
Thomas

**Comment by sdodsley** [comment]
@tpeponas you have set `schedule: replication` therefore the code doesn't even get into the section where `snap_enabled` is mentioned.
I'll have a look at this to see what is going on.

**Comment by tpeponas** [comment]
you right but same problem with code :
_if not module.params["enabled"]:
            replicate_enabled = current_repl["replicate_enabled"]
        else:
            replicate_enabled = module.params["enabled"]_
