### ISSUE TITLE
Unable to delete with purefa_dns 2

### ISSUE THREAD

**Issue by ryuyamag** [Pure-Storage-Ansible/FlashArray-Collection#507]
Thank you for providing the updated version. When I checked, the error was gone, but the DNS information was not deleted.

• Ansible version : core 2.15.5
• FlashArray Collection version: 1.23.1
• Purity version: 6.3.13/6.4.10
• FlashArray module causing the failure: purefa_dns
• An example task that fails: delete
• Response from ansible-playbook -vvvv when running a failing task: See attached
[purefa_dns_delete.yml.zip](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/13346772/purefa_dns_delete.yml.zip)

**Comment by sdodsley** [comment]
@ryuyamag Apologies - please try this
