### ISSUE TITLE
About purefa_ra's disconnect feature

### ISSUE THREAD

**Issue by ryuyamag** [Pure-Storage-Ansible/FlashArray-Collection#533]
I would like it to be possible to disconnect not only when the status is "connected" but also it is "connecting".
When enabling RA, if there is a communication problem, the status will remain in the connecting state. For this reason, it would be helpful if purefa_ra could disconnect it.
It is possible from CLI or GUI.

•	Ansible version : core 2.15.8
•	FlashArray Collection version: 1.24.0
•	Purity version: 6.4.10
•	FlashArray module causing the failure: purefa_ra

**Comment by ryuyamag** [comment]
Thank you for your prompt response.
but I got an error the attached log.
[ra.zip](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/14046202/ra.zip)

It seems not possible to disconnect.

**Comment by sdodsley** [comment]
That looks like an error from the Flasharray rather than the Ansible module. I have confirmed the updated module works on multiple arrays in our lab.

Can you perform the disconnect from the FlashArray commandline, or from the GUI?
You may need to contact support to discover the issue.

**Comment by ryuyamag** [comment]
>> Can you perform the disconnect from the FlashArray commandline, or from the GUI?
Yes, of course it works.

Well, I just realized that there were other big changes to this module yesterday.

It works when I use version 1.24.0 of purefa_ra, but not when I use the latest one.
Additionally, no error occurs if "changed": false.

Are there any differences from the environment you have confirmed?

# ansible-galaxy collection list|grep -i pure
purestorage.flasharray        1.24.0
purestorage.flashblade        1.14.0
purestorage.fusion            1.6.0

# pip3 list |grep -i pure
purestorage         1.19.0
py-pure-client      1.46.0
#

**Comment by sdodsley** [comment]
You need to apply the patch to Collection 1.26.0. You are currently running 1.24.0.
There are fundamental changes to the Collection from 1.25.0

**Comment by ryuyamag** [comment]
I just tried 1.26.0.
The result was the same, purefa_ra in 1.26.0 worked.
However, when using the latest purefa_ra, the following error is output and neither connect nor disconnect works.
`"msg": "Enabling Remote Assist failed. Error: Unidentified internal error."`
```
# ansible-galaxy collection list|grep pure
purestorage.flasharray        1.26.0
purestorage.flashblade        1.14.0
purestorage.fusion            1.6.0
```

**Comment by sdodsley** [comment]
Can we set up a session so I can see this happening live and try and debug it?

**Comment by ryuyamag** [comment]
Thank you very much for your help earlier.

I tested it with 8 arrays, and I was able to confirm that it works with 6.3.x. It didn't work on 6.4.x or 6.5.x.
However, I was able to confirm that there is no problem with ansible. My customer's purity is 6.3, so this is the solution for now. Thank you very much.
