### ISSUE TITLE
Ignore SSL Invalid Cert

### ISSUE THREAD

**Issue by cambriajw** [Pure-Storage-Ansible/FlashArray-Collection#575]
**Is your feature request related to a problem? Please describe.**
Yes, we currently are using a self sign certificate and having problems now with purestorage.flasharray.purefa_snap connecting to the array.  

**Describe the solution you'd like**
Please add an option to ignore SSL certificates that are "not secure" as they are self sign certs.  and dont have the full chain.

**Describe alternatives you've considered**
Had to add bottom 3 values to ansible.cfg to work around issue

[defaults]                          # paths to search for roles in, colon separated
library           = ./library
collections_path  = ./collections
roles_path        = ./roles
host_key_checking = false
deprecation_warnings = false
interpreter_python = auto_silent

*Additional context**

**Comment by sdodsley** [comment]
Can you please show the failure for the `purefa_snap` module?
Please show the output from `ansible-playbook -vvvv <playbook>`

**Comment by cambriajw** [comment]
`failed: [servername -> localhost] (item={'key': 'u02', 'value': {'source': 'pldb0000-u02-db-ebsp', 'target': 'servername-u02-db-ebspatch'}}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "u02", "value": {"source": "pldb0000-u02-db-ebsp", "target": "servername-u02-db-ebspatch"}}, "module_stderr": "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'PureArray01'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'PureArray01'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  warnings.warn(\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1717161433.5…`

**Comment by cambriajw** [comment]
Seems like there are some messages that were happening on the Python side.

**Comment by sdodsley** [comment]
I need the full output from the `-vvvv` please.
Also please confirm the version of the FlashArray Collection you are using and the py-pure-client SDK

**Comment by cambriajw** [comment]
`[root@test orca]# ./ansible-requirements-install.sh 
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/ansible-posix-1.5.4.tar.gz to /root/.ansible/tmp/ansible-local-2658438thvyfi7h/tmpqlqlygkp/ansible-posix-1.5.4-69ovofh0
Installing 'ansible.posix:1.5.4' to '/opt/repo/orca/collections/ansible_collections/ansible/posix'
ansible.posix:1.5.4 was installed successfully
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/purestorage-flasharray-1.28.0.tar.gz to /root/.ansible/tmp/ansible-local-2658438thvyfi7h/tmpqlqlygkp/purestorage-flasharray-1.28.0-lib9czvg
Installing 'purestorage.flasharray:1.28.0' to '/opt/repo/orca/collections/ansible_collections/purestorage/flasharray'
purestorage.flasharray:1.28.0 was installed successfully
Downloading https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-general-9.0.1.tar.gz to /root/.ansible/tmp/ansible-local-2658438thvyfi7h/tmpqlqlygkp/community-general-9.0.1-n9wwijlu
Installing 'community.general:9.0.1' to '/opt/repo/orca/collections/ansible_collections/community/general'
community.general:9.0.1 was installed successfully`

**Comment by cambriajw** [comment]
purestorage               1.19.0
py-pure-client            1.47.0
