### ISSUE TITLE
In purefa_token, main doesn't pull in the module defautls

### ISSUE THREAD

**Issue by lotaris-xx** [Pure-Storage-Ansible/FlashArray-Collection#613]
**Describe the bug**
The purefa_token module main() should grab purefa_argument_spec() and the update() the spec with module parameters, but it does not. This causes what looks like a cert error, but is actually a keyerror about disable_warnings. disable_warnings is defined in purefa_argument_spec globally.

**To Reproduce**
Use 1.29.0 or greater of the collection and try to run the purefa_token module.

**Expected behavior**
Expect the token operation to succeed.

**Additional context**
Will submit PR.

**Comment by sdodsley** [comment]
@lotaris-xx I'm not sure doing what you suggest will work. Thi smodukle is effectively a standalone module that was only added reluctantly. 
What appears to have happened is that when we added `disable_warnings` to the main util module, we forgot to add it to this module.
We'll get it fixed .

**Comment by sdodsley** [comment]
The correct method for resolving this should be in #615 
Please check this to see it it works

**Comment by lotaris-xx** [comment]
Whacky. Every other module uses the method in 614 for this property.

**Comment by lotaris-xx** [comment]
I did fix the linting and import error in #615, so it will hopefully pass pipelines now.

**Comment by lotaris-xx** [comment]
That makes sense. We use central auth on all of our arrays and for each ansible job we first create a 1day token and use that for the rest of the job and then delete the token at the end of the job. Keeps us from having to have a shared list of tokens vaulted somewhere that we have to then manage/rotate regularly. Interested to hear what the recommended workflow would be for automation across a large # of arrays, probably a good conversation for another forum.

**Comment by sdodsley** [comment]
@lotaris-xx does this patch resolve your issue?
We are going to release a new collection soon and want to add this fix into it, assuming it works for you

**Comment by lotaris-xx** [comment]
I can let you know by EOD tomorrow. Thanks, -Allen

**Comment by lotaris-xx** [comment]
Our test session has slipped to Monday, so we will update then.

**Comment by lotaris-xx** [comment]
Works great. Thanks!
