### ISSUE TITLE
Purefa_inventory giving back only "Null" as value for port information

### ISSUE THREAD

**Issue by LukasBr1337** [Pure-Storage-Ansible/FlashArray-Collection#626]
The collected infromation from purefa_iventory are only "Null" for most of the fields. 

Example:
            "CT1.FC8": {
                "connector_type": null,
                "rx_los": null,
                "rx_power": null,
                "speed": 32000000000,
                "static": {},
                "status": "ok",
                "temperature": null,
                "tx_bias": null,
                "tx_fault": null,
                "tx_power": null,
                "type": "fc_port",
                "voltage": null

Purity Version 6.5.7

**Comment by sdodsley** [comment]
Yes - this is a bug - working on a fix now.
