### ISSUE TITLE
Unable to Configure Default DS Roles on Deployment

### ISSUE THREAD

**Issue by exp-hc** [Pure-Storage-Ansible/FlashArray-Collection#672]
https://github.com/Pure-Storage-Ansible/FlashArray-Collection/blob/5d741f8cc1b6bfa3de7eb5db347938b5e27ee7ac/plugins/modules/purefa_dsrole.py#L288

With the logic at the above location, when you are configuring a DS role on a new array or DS role that has not been configured with a group, the code attempts to create a role instead of updating the existing role. 

Example of the error when attempting to set a group and group base on the ops_admin role: 
"Create Directory Service Role ops_admin failed. Error: Cannot re-create system-defined role mapping."

**Comment by sdodsley** [comment]
Please provide an example playbook with details of the DS configuration before running and then the associated failure.
Also please confirm the Purity/FA version and the Ansible Collection version.

**Comment by exp-hc** [comment]
Purity/FA version: 6.6.11
Ansible Collection: purestorage.flasharray: 1.32.0 

```- name: Map Default Roles to AD Groups
      purestorage.flasharray.purefa_dsrole:
        role: "{{ item.role }}"
        group_base: "{{ item.group_base }}"
        group: "{{ item.group }}"
        fa_url: "{{ mgmt_vip }}"
        api_token: "{{ token }}"
      delegate_to: localhost
      loop:
        - group: 'Pure Array Admin'
          group_base: 'OU=Security Groups,OU=Groups'
          role: array_admin
        - group: 'Pure Ops Admin'
          group_base: 'OU=Security Groups,OU=Groups'
          role: ops_admin
        - group: 'Pure Read Only'
          group_base: 'OU=Security Groups,OU=Groups'
          role: readonly
        - group: 'Pure Storage Admin'
          group_base: 'OU=Security Groups,OU=Groups'
          role: storage_admin```

Example Error: `(item={'group': 'Pure Ops Admin', 'group_base': 'OU=Security Groups,OU=Groups', 'role': 'ops_admin'}) => {"ansible_loop_var": "item", "changed": false, "item": {"group": "Pure Ops Admin", "group_base": "OU=Security Groups,OU=Groups", "role": "ops_admin"}, "msg": "Create Directory Service Role ops_admin failed. Error: Cannot re-create system-defined role mapping."}`

I'll fork this repo and share the workaround I used to get this working with comments although I'm sure you would prefer to fix it a different way.

**Comment by exp-hc** [comment]
Example of a workaround for system-defined roles:
https://github.com/exp-hc/FlashArray-Collection/commit/fc0c12d217b75076909123ecb6048c34fd0a8bf7

**Comment by sdodsley** [comment]
If you want to submit this as a PR then please do so and we'll potentially just use your patch.
