### ISSUE TITLE
purefa_volume does not allow to move volume from vgroup if it's part of pgroup

### ISSUE THREAD

**Issue by 212850a** [Pure-Storage-Ansible/FlashArray-Collection#674]
Starting from collection version 1.32.0 purefa_volume module does not allow to move volume from volume group if it's part of protection group.
It returns "Cannot move volume in protection groups" error. 
Why this limitation was added to collection when it is possible to do that in array GUI (Purity 6.8.5)?

**Comment by sdodsley** [comment]
@212850a we see the issue and are working on a patch for it.
