### ISSUE TITLE
purefa_snap volume

### ISSUE THREAD

**Issue by darthVikes** [Pure-Storage-Ansible/FlashArray-Collection#675]
When trying to snapshot a volume with purefa_snap

- name: Take Volume Snapshots of "{{ ora_source }}" 
  purestorage.flasharray.purefa_snap:
    name: "{{ item.value.source }}"
    suffix: "{{ pg_suffix }}-{{ snap_date }}"
    fa_url: "{{ source_pure }}"
    api_token: "{{ api_token }}"
    state: present
    disable_warnings: true
  loop: "{{ purevolmap|dict2items }}"
  delegate_to: localhost
  register: volumes

Seeiog this exception:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: post_volume_snapshots() got an unexpected keyword argument 'allow_throttle'
failed: [server2-> localhost] (item={'key': 'u03', 'value': {'source': 'server1', 'target': 'server2'}}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "u03", "value": {"source": "server1", "target": "server2"}}, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1733061980.610246-410-41724284666902/AnsiballZ_purefa_snap.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1733061980.610246-410-41724284666902/AnsiballZ_purefa_snap.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1733061980.610246-410-41724284666902/AnsiballZ_purefa_snap.py\", line 47, in invoke_mod…

**To Reproduce**
Run playbook, happened multiple each time so was repeatable.

**Expected behavior**
Would finish the snapshot

**Additional context**
purestorage.flasharray-1.31.1

ansible [core 2.14.17]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.19 (main, Sep 11 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

**Comment by sdodsley** [comment]
@darthVikes please confirm that you have the latest version of the `py-pure-client` SDK installed - it is currently at 1.57.0
We have released Collection 1.32.0 as well, so please upgrade to that at as well.
If the issue still persists please provide the Purity//FA version you are using as well as the complete traceback from the `-vvvv` response.

**Comment by darthVikes** [comment]
Purity//FA :  6.5.8

pip3 list | grep pure
purestorage               1.19.0
py-pure-client            1.47.0

So upgrade py-pure-client to 1.57?   

What is the collection?  
Do I need to upgrade purestorage too?
Is this a known issue with my current version?

Thanks!

**Comment by sdodsley** [comment]
Yes - upgrade py-pure-client to 1.57.0 - that will probably fix it.
You need to keep this SDK package at the latest version as this is what controls the underlying API communication with the FlashArray and references the latest parameters required.
The Collection is the Ansible modules in purestorage.flasharray.
You upgrade using `ansible-galaxy collection install --upgrade purestorage.flasharray`

**Comment by darthVikes** [comment]
Got it.  thanks!

**Comment by darthVikes** [comment]
Also have the purestorage.flasharray in my ./collections/requirements.yaml  to keep that also up to date.

---
collections:
  - name: purestorage.flasharray
    source: https://galaxy.ansible.com

  - name: ansible.posix
    source: https://galaxy.ansible.com

  - name: community.general
    source: https://galaxy.ansible.com

**Comment by darthVikes** [comment]
Thanks, that seemed to resolve it.
