### ISSUE TITLE
List volumes in protection group

### ISSUE THREAD

**Issue by Agent-E11** [Pure-Storage-Ansible/FlashArray-Collection#681]
Is there a way to get the list of volumes that are in a protection group?

The equivalent command would be:

```sh
# SSH'd into the NAS
user@server> purepgroup listobj --type vol <pgroup name>
```

The statement "this collection can be used to perform any task that you would normally perform using the command-line or GUI on a FlashArray" suggests that it is possible, but I cannot figure out how.

**Comment by sdodsley** [comment]
You can do this with the `purefa_info` module, specifically setting the parameter `gather_subset: pgroups`. The response will be a dict of all the protection groups, and in each there will be a `volumes` section.
